%create individual powerspectrum tables for each drug in list for mixed
%model

clear;
%add eeglab to path and start its init file%
addpath('eeglab2021.0\'); 
eeglab;

%all drugs for mixed model
% meds=["Risperidone", "Olanzapine", "Quetiapine", "Aripiprazole", "Ziprasidone", "Haloperidol", ...
%     "Cariprazine", "Asenapine", "Benperidol", "Bromperidol", "Chlorprotixene", "Flupentixole", ...
%     "Fluphenazine", "Fluspirilene", "Levomepromazine", "Melperone", "Perazin", "Perphenazine",...
%     "Pimozide", "Pipamperon", "Prothipendyl", "Sertindole", "Sulpiride", "Thioridazine",...
%     "Zuclopenthixol", "Clozapin", ...
%     "Citalopram", "Escitalopram", "Sertraline", "Paroxetine", "Fluoxetine", "Bupropion", "Venlafaxine", "Mirtazapine", ...
%     "Trazodone", "Agomelatin", "Amitriptyline", "Clomipramin", "Doxepin", "Duloxetin", "Imipramin", ...
%     "Maprotilin", "Mianserin", "Milnacipran", "Moclobemid", "Nortriptylin", "Reboxetin",...
%     "Tranylcypromin", "Trimipramin",...
%     "Lithium"];

meds=["Quetiapine", "Aripiprazole", "Ziprasidone", "Haloperidol", ...
    "Cariprazine", "Asenapine", "Benperidol", "Bromperidol", "Chlorprotixene", "Flupentixole", ...
    "Fluphenazine", "Fluspirilene", "Levomepromazine", "Melperone", "Perazin", "Perphenazine",...
    "Pimozide", "Pipamperon", "Prothipendyl", "Sertindole", "Sulpiride", "Thioridazine",...
    "Zuclopenthixol", "Clozapin", ...
    "Citalopram", "Escitalopram", "Sertraline", "Paroxetine", "Fluoxetine", "Bupropion", "Venlafaxine", "Mirtazapine", ...
    "Trazodone", "Agomelatin", "Amitriptyline", "Clomipramin", "Doxepin", "Duloxetin", "Imipramin", ...
    "Maprotilin", "Mianserin", "Milnacipran", "Moclobemid", "Nortriptylin", "Reboxetin",...
    "Tranylcypromin", "Trimipramin",...
    "Lithium"];

%import necessary functions
d = functionsForTUHData;
funcEDF = functionsForEDFFiles;

drive="D:/";

for i=1:length(meds)

    medicine = strcat(meds(i));
    folder = strcat(drive, 'EDFData\', medicine);

    folder = strcat(folder, '\CleanData');
    listEDF = d.createFileList('edf',folder);
    savefile = strcat(drive, 'Results\Powerspectrum\', medicine, '_powerspectrumMixedModel.xls');
    removedFiles = strcat(drive, 'Results\Powerspectrum\', medicine, '_removedFilesEpochs.txt');

    %calculates powerspectrum for mixed model for a list of edf files
    funcEDF.calculatePowerForBands(listEDF, savefile, removedFiles, medicine);

end




